language: c
compiler:
  - gcc

before_install:
  - sudo apt-add-repository -y ppa:vala-team/ppa
  - sudo apt-add-repository -y ppa:bake-team/releases
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq valac bake libgtk-3-dev check libjson-glib-dev libsqlite3-dev yasm > /dev/null

before_script:
  #installing libsodium, needed for toxcore
  - _libsodium_ver=0.7.0
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - pushd libsodium
  - git checkout tags/${_libsodium_ver} > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #installing libopus, we'll need this for future audio encoding/decoding
  - _opus_ver=1.0.3
  - wget http://downloads.xiph.org/releases/opus/opus-${_opus_ver}.tar.gz > /dev/null
  - tar xzf opus-${_opus_ver}.tar.gz > /dev/null
  - pushd opus-${_opus_ver}
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #installing vpx
  - git clone https://chromium.googlesource.com/webm/libvpx.git > /dev/null
  - pushd libvpx
  - ./configure --prefix=/usr --enable-shared > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #installing toxcore
  - git clone http://github.com/irungentoo/toxcore.git > /dev/null
  - pushd toxcore
  - autoreconf -i > /dev/null
  - ./configure --prefix=/usr --disable-ntox --disable-daemon > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - popd
  #creating libraries links and updating cache
  - sudo ldconfig > /dev/null

script:
  - bake
  - sudo bake install
